contact-tracing/force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

contact-tracing/force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

contact-tracing/force-app/main/default/objects/Person__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

contact-tracing/force-app/main/default/objects/Person__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

contact-tracing/force-app/main/default/classes/CTPersonTriggerHandler.cls
public with sharing class CTPersonTriggerHandler {

    /** before insert operation for person object
     * make sure the health status is green
     * generate unique token for each record
     */
    
    public static void beforeInsert(List<Person__c> newRecords){
        for(Person__c person : newRecords){
            //update person status to green
            person.Health_Status__C = 'Green';
            //genetate unique token
            person.Token__c = CTPersonController.getToken(person.Mobile__c);
        }
    }
// Before Update operson for Person__C object

    public static void beforeUpdate(List<Person__c> newRecords, Map<id, Person__c> oldRecordsMap){

        for(Person__c person : newRecords){

            //check if status changed in this trancation 
            // also upate Status_Update_Date__c

            if( person.Health_Status__C != oldRecordsMap.get(person.id).Health_Status__C){

                person.Status_Update_Date__c = Date.Today();
            }
        }
    }
}