contact-tracing/force-app/main/default/objects/People_Tracing__c/People_Tracing__c.object-meta.xml
<CustomObject>
    <label>People Tracing</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People Tracing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

contact-tracing/force-app/main/default/objects/People_Tracing__c/fields/Contact_Date__c.field-meta.xml
<CustomField>
    <fullName>Contact_Date__c</fullName>
    <label>Contact Date</label>
    <type>Date</type>
</CustomField>

contact-tracing/force-app/main/default/objects/People_Tracing__c/fields/Person_1__c.field-meta.xml
<CustomField>
    <fullName>Person_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 1</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Primary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

contact-tracing/force-app/main/default/objects/People_Tracing__c/fields/Person_2__c.field-meta.xml
<CustomField>
    <fullName>Person_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Person 2</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Secondary Close Contacts</relationshipLabel>
    <relationshipName>Close_Contacts2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

contact-tracing/force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

contact-tracing/force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

contact-tracing/force-app/main/default/objects/Person__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

contact-tracing/force-app/main/default/classes/CTPeopleTracingController.cls
public with sharing class CTPeopleTracingController {

    public static List<People_Tracing__c> getTraces(string PersonId){

        return [SELECT Id, Contact_Date__c, Person_1__c, Person_1__r.Health_Status__C, Person_1__r.Token__c, Person_2__c, Person_2__r.Health_Status__C, Person_2__r.Token__c 
                   FROM People_Tracing__c 
                   WHERE Person_1__c = :PersonId 
                   OR Person_2__C = :PersonId
                  ORDER BY Contact_Date__c DESC];
    }

    public static List<People_Tracing__c> checkDuplicates(List<People_Tracing__c> newPeopleTraces){
          
      Set<Id> personIds = new Set<Id>();
    for(People_Tracing__c Trace : newPeopleTraces){
      personIds.add(Trace.Person_1__c);
      personIds.add(Trace.Person_2__c);
    }
    
    //List of duplicate records

    List<People_Tracing__c> duplicate = new List<People_Tracing__c>();

    // map id and set id

    Map<Id, set<Id>> mapOfExistingRecords = new Map<Id, set<Id>>();
    
    // query existing records
    List<People_Tracing__c> existingRecords = [ Select Id, Person_1__C, Person_2__c 
                                                 FROM People_Tracing__c
                                                 WHERE Person_1__c IN :personIds 
                                                 OR PErson_2__c IN :personIds];
     
     if(existingRecords != null && existingRecords.size()>0){
        for(People_Tracing__c Traces : existingRecords){
            if(!mapOfExistingRecords.containsKey(Traces.Person_1__c)){

                mapOfExistingRecords.put(Traces.Person_1__c, new set<Id>());
            }
            mapOfExistingRecords.get(Traces.Person_1__C).add(Traces.Person_2__c);

            //build map for person 2
            if(!mapOfExistingRecords.containsKey(Traces.Person_2__c)){

                mapOfExistingRecords.put(Traces.Person_2__c, new set<Id>());
            }
            mapOfExistingRecords.get(Traces.Person_2__C).add(Traces.Person_1__c);
        }
       // loop over existring record to find duplicates
        for(People_Tracing__c Trace : newPeopleTraces)
       
        //check for duplicates in map
        if(
            (mapOfExistingRecords.containsKey(Trace.Person_1__c) && mapOfExistingRecords.get(Trace.Person_1__c).contains(Trace.Person_2__c))
            ||
            (mapOfExistingRecords.containsKey(Trace.Person_2__c) && mapOfExistingRecords.get(Trace.Person_2__c).contains(Trace.Person_1__c))
          )
        {
            duplicate.add(Trace);
        }
    }


     return duplicate;
}
     



    }